-- Validation Rules for regles_validation
INSERT INTO regles_validation (nom_colonne, type_regle, valeur_regle, message_erreur, colonne_dependante, valeur_dependante, colonne_cible, valeur_cible_attendue) VALUES
('niv_resp', 'DOMAINES', 'niveaux_responsabilite', 'La valeur de niveau de responsabilité est hors domaine autorisé.', NULL, NULL, NULL, NULL),
('id_plafond', 'REQUIRED_IF', NULL, 'Le champ id_plafond est obligatoire si type_credit est 900.', 'type_credit', '900', NULL, NULL),
('num_contrat_credit', 'UNIQUE', NULL, 'Le numéro de contrat de crédit doit être unique.', NULL, NULL, NULL, NULL),
('num_contrat_credit', 'FORMAT', 'CR+[code_banque]+[date.HHMMSS]', 'Le format du numéro de contrat de crédit est invalide.', NULL, NULL, NULL, NULL),
('num_contrat_credit', 'NOT_EDITABLE', NULL, 'Le numéro de contrat de crédit ne doit pas être modifié.', NULL, NULL, NULL, NULL),
('code_monnaie', 'DOMAINES', 'monnaies', 'La valeur de code monnaie est hors domaine autorisé.', NULL, NULL, NULL, NULL),
('RIB', 'LENGTH', '20', 'Le RIB doit comporter exactement 20 caractères.', NULL, NULL, NULL, NULL),
('code_pays', 'DOMAINES', 'pays', 'La valeur de code pays est hors domaine autorisé.', NULL, NULL, NULL, NULL),
('code_pays', 'DEFAULT_IF_NULL', '012', 'Le code pays est renseigné à 012 (Algérie) si vide.', NULL, NULL, NULL, NULL),
('code_agence', 'DOMAINES', 'agences', 'La valeur de code agence est hors domaine autorisé.', NULL, NULL, NULL, NULL),
('code_wilaya', 'REQUIRED_IF', NULL, 'Le code wilaya est obligatoire si le pays est l’Algérie.', 'code_pays', '012', NULL, NULL),
('code_wilaya', 'DOMAINES', 'wilayas', 'La valeur de code wilaya est hors domaine autorisé.', NULL, NULL, NULL, NULL),
('code_wilaya', 'MUST_BE_NULL_IF', NULL, 'Le code wilaya ne doit pas être renseigné si le pays n’est pas l’Algérie.', 'code_pays', '!=012', NULL, NULL),
('code_activite', 'DOMAINES', 'activites_credit', 'La valeur de code activité est hors domaine autorisé.', NULL, NULL, NULL, NULL),
('type_credit', 'DOMAINES', 'types_credit', 'La valeur de type crédit est hors domaine autorisé.', NULL, NULL, NULL, NULL),
('type_credit', 'FORBIDDEN_VALUES_IF', '050,051,052,080', 'Type crédit interdit pour débiteur entreprise.', 'debiteur_type', 'entreprise', NULL, NULL),
('situation_credit', 'DOMAINES', 'situations_credit', 'La valeur de situation crédit est hors domaine autorisé.', NULL, NULL, NULL, NULL),
('situation_credit', 'EQUALS_IF', '900', 'La situation crédit doit être 900 si type_credit est 900.', 'type_credit', '900', 'situation_credit', '900'),
('classe_retard', 'DOMAINES', 'classes_retard', 'La valeur de classe retard est hors domaine autorisé.', NULL, NULL, NULL, NULL),
('classe_retard', 'REQUIRED_IF', NULL, 'Classe retard doit être renseignée si situation_credit est dans [010,011,012,013,015].', 'situation_credit', '010,011,012,013,015', NULL, NULL),
('classe_retard', 'MUST_BE_NULL_IF', NULL, 'Classe retard ne doit pas être renseignée si situation_credit est dans [001,002,020,900,014,018,005].', 'situation_credit', '001,002,020,900,014,018,005', NULL, NULL),
('classe_retard', 'MUST_BE_NULL_IF', NULL, 'Classe retard ne doit pas être renseignée si id_plafond est 900.', 'id_plafond', '900', NULL, NULL),
('duree_initial', 'DOMAINES', 'durees_credit', 'La valeur de durée initiale est hors domaine autorisé.', NULL, NULL, NULL, NULL),
('duree_initial', 'FORBIDDEN_VALUES', '000', 'La durée initiale ne doit pas être 000.', NULL, NULL, NULL, NULL),
('duree_initial', 'EQUALS_IF', '999', 'La durée initiale doit être 999 si situation_credit est 001.', 'situation_credit', '001', 'duree_initial', '999'),
('duree_initial', 'FORBIDDEN_VALUES_IF', '999', 'La durée initiale ne doit pas être 999 si situation_credit n’est pas 001.', 'situation_credit', '!=001', NULL, NULL),
('duree_initial', 'EQUALS_IF', '900', 'La durée initiale doit être 900 si type_credit est 900.', 'type_credit', '900', 'duree_initial', '900'),
('duree_initial', 'FORBIDDEN_VALUES_IF', '900', 'La durée initiale ne doit pas être 900 si type_credit n’est pas 900.', 'type_credit', '!=900', NULL, NULL),
('duree_rest', 'DOMAINES', 'durees_credit', 'La valeur de durée restante est hors domaine autorisé.', NULL, NULL, NULL, NULL),
('duree_rest', 'REQUIRED_IF', NULL, 'La durée restante doit être renseignée si credit_accorde est renseigné.', 'credit_accorde', 'NOT_NULL', NULL, NULL),
('duree_rest', 'EQUALS_IF', '999', 'La durée restante doit être 999 si situation_credit est 001.', 'situation_credit', '001', 'duree_rest', '999'),
('duree_rest', 'EQUALS_IF', '900', 'La durée restante doit être 900 si type_credit est 900.', 'type_credit', '900', 'duree_rest', '900'),
('credit_accorde', 'EQUALS_IF', '0', 'Le crédit accordé doit être 0 si type_credit est 900.', 'type_credit', '900', 'credit_accorde', '0'),
('credit_accorde', 'EQUALS_IF', '0', 'Le crédit accordé doit être 0 si type_credit est 001.', 'type_credit', '001', 'credit_accorde', '0'),
('credit_accorde', 'GREATER_THAN_IF', '0', 'Le crédit accordé doit être > 0 pour les autres types de crédit.', 'type_credit', 'AUTRES', NULL, NULL),
('solde_restant', 'REQUIRED', NULL, 'Le solde restant est obligatoire.', NULL, NULL, NULL, NULL),
('solde_restant', 'EQUALS_IF', '0', 'Le solde restant doit être 0 si type_credit n’est pas 900 et situation_credit est 900.', 'type_credit', '!=900', 'situation_credit', '900'),
('solde_restant', 'EQUALS_IF', '0', 'Le solde restant doit être 0 si situation_credit est dans [001,020].', 'situation_credit', '001,020', 'solde_restant', '0'),
('cout_total', 'REQUIRED_IF', NULL, 'Le coût total est obligatoire pour type_credit dans [050,051,052] et débiteur i1 ou i2.', 'type_credit', '050,051,052', 'debiteur_type', 'i1,i2'),
('cout_total', 'MUST_BE_NULL_OR_ZERO_IF', NULL, 'Le coût total ne doit pas être renseigné ou doit être 0 si type_credit dans [050,051,052] et situation_credit dans [001,005,020,018].', 'type_credit', '050,051,052', 'situation_credit', '001,005,020,018'),
('mensualite', 'REQUIRED_IF', NULL, 'La mensualité est obligatoire pour type_credit dans [050,051,052].', 'type_credit', '050,051,052', NULL, NULL),
('mensualite', 'MUST_BE_NULL_IF', NULL, 'La mensualité ne doit pas être renseignée si type_credit n’est pas dans [050,051,052].', 'type_credit', '!=050,051,052', NULL, NULL),
('mensualite', 'MUST_BE_NULL_OR_ZERO_IF', NULL, 'La mensualité ne doit pas être renseignée ou doit être 0 si type_credit dans [050,051,052] et situation_credit dans [001,005,020,018].', 'type_credit', '050,051,052', 'situation_credit', '001,005,020,018'),
('garantie', 'REQUIRED', NULL, 'La garantie est obligatoire.', NULL, NULL, NULL, NULL),
('garantie_montant', 'GREATER_THAN', '0', 'Le montant de la garantie doit être supérieur à 0.', NULL, NULL, NULL, NULL),
('garantie_montant', 'EQUALS_IF', '0', 'Le montant de la garantie doit être 0 si type_garantie est 999.', 'type_garantie', '999', 'garantie_montant', '0');
